development:
  secret_key_base: 2b8821891787bb3a0768ac609c2b86af1b091bd8971860f29d4ef7134cf36e5cd8aee85f5d551bb5da5dea6ec2893b4adb2c8a8bfb52f518f71921fd9a6dc125
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>

test:
  secret_key_base: ad1546c38d7dd5b47745aec0db4aaf38f43f185223a9da3fe581d504c3d5d572764f1e07c9495c1acde13af1402ecae76e6dc9cd84e87aebf4d325e47edd292e
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_sid: <%= ENV["TWILIO_SID"] %>
  twilio_token: <%= ENV["TWILIO_TOKEN"] %>
  twilio_number: <%= ENV["TWILIO_NUMBER"] %>
